### ISSUE TITLE
Node driver paths don't resolve correctly on Windows

### ISSUE THREAD

**Issue by djholly123** [Putaitu/putaitu-cms#211]
Hi 

Have followed the instructions to spin up demo project and cant start it

Can I set the path in config somewhere ? I could not find this in docs sorry

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'D:\D:\git\mchb1'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.mkdirRecursively (D:\git\mchb1\node_modules\hashbrown-driver\HashBrown.js:157:20)
    at Function.ensureLocations (D:\git\mchb1\node_modules\hashbrown-driver\HashBrown.js:100:22)
    at Object.

**Comment by mrzapp** [comment]
HashBrown hasn't been tested on systems using non standard paths,
unfortunately. The fix is to use the "path" library. Another fix was
proposed earlier this week, but not implemented.

Would you mind trying to patch this? I only have Linux machines around me
right now.

If not, I will get on it as soon as I can.

**Comment by djholly123** [comment]
Thanks I may get time to try the workaround

**Comment by mrzapp** [comment]
The latest commit to the node driver has resolved this issue. Be sure to get the latest stable version of HashBrown, as a critical fix related to the example project was just committed.
