### ISSUE TITLE
Documentation for the API auth should be more clear

### ISSUE THREAD

**Issue by mrzapp** [Putaitu/putaitu-cms#233]

**Comment by mrzapp** [comment]
@milesleif please let me know which format you'd prefer

**Comment by milesleif** [comment]
@mrzapp I had a hard time understanding that on http://hashbrown.rocks/docs/api/#UserController the parameter `credential` is actually not a key for anything and that I needed to POST the plain object

```
{
  username: 'username'
  password: 'password'
}
```

to the path `/api/user/login` with an optional `?persist=true` added to the url.

When I compare this structure to the other paragraphs of the manual this actually makes a lot of sense, since the parameter names are never used as part of key/value-pairs – and when looking at all the string parameters it becomes clear that they belong to the url, even when posting additional objects. 

So I am not sure if there is a need for changing the format here. I think it would help most to provide a plain example, maybe like so



## Example POST /api/user/login


### url 
`http://your-hashbrown-cms.com/api/user/long?persist=true`

### body
```
{
  username: 'your-username'
  password: 'your-password'
}
```
