### ISSUE TITLE
Add formatting buttons and syntax highlighting to markdown editor on richTexts

### ISSUE THREAD

**Issue by milesleif** [Putaitu/putaitu-cms#346]
Following the discussion in https://github.com/HashBrownCMS/hashbrown-cms/issues/344

The `markdown`-tab of the `richText` fields at the moment only provides an input field for plain text. 

We want to make our clients use markdown as often as possible, but memorizing (and recognizing) all possible markdown tags is hard.

This ticket suggests an implementation of a basic formatting toolbar to insert markdown code easily and format existing markdown. On top of that it would be very handy to see markdown formatting highlighted in some way.

Inspiration comes from 

https://github.com/sylvainjule/kirby-markdown-field

which makes use of [codmirror](https://github.com/codemirror/CodeMirror) to achieve that.

**Comment by mrzapp** [comment]
@milesleif this turned out to be a whole can of worms, since apparently the `execCommand` is being abandoned by Firefox, so we have to build our own formatters now. I'm more or less done with that part, so next step is to figure out how to manage selections with markdown.

We used to ship with CodeMirror, but it's a huge overhead for little gain, so I'm reluctant to bundling it back in.

**Comment by mrzapp** [comment]
@milesleif I've caved in and started to implement both CodeMirror for HTML/markdown and ProseMirror for the RTE. It's currently in a semi-usable state, although links and media insertions don't work yet.

When this is over, we'll have syntax highlighting, smart indentation, tab handling and all that good stuff. I'll make sure to implement CodeMirror in the JSON editor too.

**Comment by mrzapp** [comment]
@milesleif I'm struggling a bit to get lists to work properly, mainly because the ProseMirror documentation doesn't seem to provide a good, clean example of how to implement it.

Other than that, all editors should be working. Could you test the latest `develop` branch out sometime and let me know if things behave as you'd expect?
